executableName=python record_processor.py
applicationName=booking-kcl-practice
streamName=REPLACE_STREAM_NAME
regionName=eu-west-1
initialPositionInStream=TRIM_HORIZON
AWSCredentialsProvider=DefaultAWSCredentialsProviderChain

